AWSTemplateFormatVersion: 2010-09-09
Description: Basic EC2 Instances

Resources:
  DevEC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      ImageId: ami-01816d07b1128cd2d
      InstanceType: t2.micro
      KeyName: us-east-1-keypair
      SecurityGroups:
        - default
