AWSTemplateFormatVersion: 2010-09-09
Description: Basic EC2 Instances

Parameter:
  MyKeyName:
    Description: Select the keyname from list
    Type: AWS::EC2::KeyPair::KeyName
  MyAvailabilityZone:
    Description: Select the availability zone
    Type: String
    Default: us-east-2a
    AllowedValues:
      - us-east-2a
      - us-east-2b
      - us-east-2c
  MyInstanceType:
    Description: Select instance type
    Type: AWS::SSM::Parameter::Value<String>

Mappings:
  MyRegionMap:
    us-east-2:
      HVM64:  ami-01816d07b1128cd2d
    us-east-1:
      HVM64:  ami-01816d07b1128cd2d

  MyEnvironmentMap:
    dev:
      instanceType: t2.micro
    prod:
      instanceType: t2.small

Resources:
  DevEC2Instance:
    Type: AWS::EC2::Instance
    CreationPolicy:
      ResourceSignal:
        TimeOut:  PT5M
    Metadata:
      Comment: Deploy a sample tomcat application
      AWS::CloudFormation::Init:
        configSets:
          SingleAppCS:
            - App1
          DualAppCS:
            - configSet:  "SingleAppCS"
            - App2
          default:
            - configSet:  "DualAppCS"
        App1:
          packages:
            yum:
              java-1.8.0-openjdk.x86_64:  []
              tomcat8:  []
          groups:
            groupone: {}
            grouptwo:
              gid: "501"
          users:
            user1:
              groups:
                - groupone
                - grouptwo
              uid:  "501"
              homeDir:  "/tmp"
          sources:
            /tmp: "https://s3.us-east-2.amazonaws.com/codeanddeploymentbucket/data/demo.zip"
          files:
          services:
            sysvinit:
              tomcat8:
                ensureRunning:  "true"
                enabled:  "true"
        App2:
          commands:
            test1:
              cmd:  "chmod 777 demo.war"
              cwd:  "/tmp"
            test2:
              cmd:  "chmod 666 artifact.war"
              cwd:  "/etc/bin"
    Properties:
      ImageId: !FindInMap
        - MyRegionMap
        - !Ref 'AWS::Region'
        - HVM64
      InstanceType: !Ref MyInstanceType
      KeyName: !Ref MyKeyName
      AvailabilityZone: !Ref MyAvailabilityZone
      SecurityGroups:
        - default
        - Ref: SSHSecurityGroup

  SSHSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: new SSH Group
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: '22'
          ToPort: '22'
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: '8080'
          ToPort: '8080'
          CidrIp: 0.0.0.0/0

  DevEIP:
    Type: AWS::EC2::EIP
    Properties:
      InstanceId: !Ref DevEC2Instance